import Header from '@/components/Header'
import '../globals.css'
import { Inter } from 'next/font/google'
import {Sidebar} from '@/components/Sidebar/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className='flex justify-center h-full items-start'>
          <Sidebar />
          <main className="w-full relative app p-1 h-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}